### ISSUE TITLE
Test gym and client

### ISSUE THREAD

**Issue by flaviomor** [dasGringuen/assetto_corsa_gym#4]
Hello,

I was able to go through you procedure. Nevertheless, I get an error when I try to execute the notebooks test_gym or test_client. The environment is well created but the error appears when I try to execute this cell:

static_info = env.client.simulation_management.get_static_info()
ac_mod_config = env.client.simulation_management.get_config()

logger.info("Static info:")
for i in static_info:
    logger.info(f"{i}: {static_info[i]}")
logger.info("AC Mod config:")
for i in ac_mod_config:
    logger.info(f"{i}: {ac_mod_config[i]}")
    
Here is th error:

---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
Cell In[4], line 1
----> 1 static_info = env.client.simulation_management.get_static_info()
      2 ac_mod_config = env.client.simulation_management.get_config()
      4 logger.info("Static info:")

File [~\assetto_corsa_gym\assetto_corsa_gym\AssettoCorsaEnv\ac_client.py:44](http://localhost:8888/~/assetto_corsa_gym/assetto_corsa_gym/AssettoCorsaEnv/ac_client.py#line=43), in SimulationManagement.get_static_info(self)
     43 def get_static_info(self):
---> 44     static_info = eval(self.send_message("get_static_info", wait_response=True))
     45     track_full_name = f"{static_info['TrackName']}"
     46     if static_info['TrackConfiguration']:

File [~\assetto_corsa_gym\assetto_corsa_gym\AssettoCorsaEnv\ac_client.py:25](http://localhost:8888/~/assetto_corsa_gym/assetto_corsa_gym/AssettoCorsaEnv/ac_client.py#line=24), in SimulationManagement.send_message(self, message, wait_response)
     23 def send_message(self, message, wait_response=False):
     24     with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
---> 25         s.connect((self.host, self.port))
     26         s.sendall(message.encode())
     27         s.settimeout(5)

ConnectionRefusedError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

I have the impression this indicates that the Python script is trying to establish a connection to a server or service at a specific IP address and port.

Can you help me please ?

**Comment by dasGringuen** [comment]
Hi,

The communication between the client script and AC is done via UDP. Our plugin in AC opens a UDP server and waits for new connections. In your case, for some reason, the client script is unable to reach the server (AssettoCorsa plugin), which is set to **localhost** by default.

Could you please post the logs of the AC plugin? See the first response in this issue: [link to issue](https://github.com/dasGringuen/assetto_corsa_gym/issues/2).

Adrian

**Comment by flaviomor** [comment]
Sorry but I do not know how to launch the context manager... Can you explain please ?

**Comment by dasGringuen** [comment]
It seems that you're using a different version of Gym than expected. The newer versions of Gym return ***terminated*** and ***truncated*** instead of ***done***, which is not compatible with the current setup. Are you using gym==0.21.0 as written in the requirements?

We should upgrade to the newer version at some point.

**Comment by dasGringuen** [comment]
> Sorry but I do not know how to launch the context manager... Can you explain please ?

You just install it. No need to launch it
