### ISSUE TITLE
Gear does not change

### ISSUE THREAD

**Issue by youwyu** [dasGringuen/assetto_corsa_gym#7]
In ac_client.py, the GEAR does not change, so how can the vehicle move?

**Comment by dasGringuen** [comment]
We were using the autoshift from AC. If you want to experiment with manual shift, some functionality needs to be implemented in `ac_client`. and in `car_control.py`. [See here](https://github.com/dasGringuen/assetto_corsa_gym/blob/a90db0a8b164164e11412857b396bf6874462976/assetto_corsa_gym/AssettoCorsaEnv/car_control.py#L70)

**Comment by youwyu** [comment]
Thank you. I have a new issue, that "reset" does not do anything. In Python log, I can see sensor_par Received: reset.

**Comment by dasGringuen** [comment]
This usually happens if you don't have ContextManager installed. The reset functionality within the plugin comes from that mod.

**Comment by youwyu** [comment]
I think I have followed the process to install.
![image](https://github.com/user-attachments/assets/e3b1a108-3116-42dc-bcfc-3343e36b70ca)
I also launch AC from contextmanager since it seems easier than running from the game.
![image](https://github.com/user-attachments/assets/2e941ef6-6c69-4a8a-aced-0527188b911c)

**Comment by dasGringuen** [comment]
ah that's right. I will update the readme. We were using: ***Challenge -> hotlap*** which also works.

**Comment by youwyu** [comment]
Thank you very much for the help.
